# Generated by Django 5.0.6 on 2026-06-25 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('live_sessions', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('topic_title', models.CharField(max_length=120)),
                ('instructor_name', models.CharField(max_length=150)),
                ('session_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('mistakes', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('instructor_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scheduling.booking')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='live_sessions.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'ai_reports',
                'indexes': [models.Index(fields=['student', '-session_date'], name='ai_reports_student_a9271c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aireport',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'ready'), _negated=True), models.Q(('overall_score__isnull', False), ('generated_at__isnull', False)), _connector='OR'), name='chk_ready_report_complete'),
        ),
    ]
