# Generated by Django 5.0.6 on 2026-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='fallback_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aireport',
            name='provider_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
