# Generated by Django 5.0.6 on 2026-07-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_reports', '0002_aireport_content_aireport_fallback_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='instructor_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
