# Generated by Django 5.0.6 on 2026-06-25 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('payment_approved', 'Payment approved'), ('payment_rejected', 'Payment rejected'), ('booking_confirmed', 'Booking confirmed'), ('session_reminder', 'Session reminder'), ('report_ready', 'Report ready')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='notificatio_user_id_cba35e_idx')],
            },
        ),
    ]
