# Generated by Django 5.0.6 on 2026-07-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_approved', 'Payment approved'), ('payment_rejected', 'Payment rejected'), ('payment_info_requested', 'Payment info requested'), ('booking_confirmed', 'Booking confirmed'), ('new_booking', 'New booking'), ('booking_cancelled', 'Booking cancelled'), ('session_reminder', 'Session reminder'), ('report_ready', 'Report ready')], max_length=40),
        ),
    ]
