# Generated by Django 5.0.6 on 2026-06-25 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('payment_approve', 'Payment approve'), ('payment_reject', 'Payment reject'), ('payment_reopen', 'Payment reopen'), ('subscription_extend', 'Subscription extend'), ('subscription_topup', 'Subscription top-up'), ('refund_note', 'Refund note'), ('booking_cancel_override', 'Booking cancel override')], max_length=40)),
                ('target_table', models.CharField(max_length=60)),
                ('target_id', models.UUIDField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_actions',
                'indexes': [models.Index(fields=['target_table', 'target_id'], name='admin_actio_target__ce3fc6_idx'), models.Index(fields=['admin', '-created_at'], name='admin_actio_admin_i_3b7b37_idx'), models.Index(fields=['action_type', '-created_at'], name='admin_actio_action__70c639_idx')],
            },
        ),
    ]
