# Generated by Django 5.0.6 on 2026-07-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action_type',
            field=models.CharField(choices=[('payment_approve', 'Payment approve'), ('payment_reject', 'Payment reject'), ('payment_request_info', 'Payment request info'), ('payment_reopen', 'Payment reopen'), ('subscription_extend', 'Subscription extend'), ('subscription_topup', 'Subscription top-up'), ('refund_note', 'Refund note'), ('booking_cancel_override', 'Booking cancel override')], max_length=40),
        ),
    ]
