# Generated by Django 5.0.6 on 2026-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0004_alter_adminaction_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("payment_approve", "Payment approve"),
                    ("payment_reject", "Payment reject"),
                    ("payment_request_info", "Payment request info"),
                    ("payment_reopen", "Payment reopen"),
                    ("subscription_extend", "Subscription extend"),
                    ("subscription_topup", "Subscription top-up"),
                    ("refund_note", "Refund note"),
                    ("booking_cancel_override", "Booking cancel override"),
                    ("schedule_approve", "Schedule approve"),
                    ("schedule_reject", "Schedule reject"),
                    ("schedule_reassign", "Schedule reassign instructor"),
                    ("user_status_changed", "User status changed"),
                    ("user_role_changed", "User role changed"),
                    ("plan_created", "Plan created"),
                    ("plan_updated", "Plan updated"),
                ],
                max_length=40,
            ),
        ),
    ]
