# Generated by Django 5.0.6 on 2026-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='scheduled', max_length=20),
        ),
    ]
