# Generated by Django 5.0.6 on 2026-07-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0002_alter_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='instructor_notes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
