# Generated by Django 5.0.6 on 2026-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_sessions", "0003_session_instructor_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="agora_channel",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
