# Generated by Django 5.0.6 on 2026-06-25 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('billing', '0002_payment_proof_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentproof',
            name='chk_decided_proof_has_reviewer',
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paymentproof',
            constraint=models.CheckConstraint(check=models.Q(('status', 'pending_review'), models.Q(('reviewed_by__isnull', False), ('reviewed_at__isnull', False)), _connector='OR'), name='chk_decided_proof_has_reviewer'),
        ),
    ]
