# Generated by Django 5.0.6 on 2026-07-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_paymentproof_chk_decided_proof_has_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs more information')], default='pending_review', max_length=20),
        ),
    ]
