# Generated by Django 5.0.6 on 2026-07-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_paymentproof_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='currency',
            field=models.CharField(default='SDG', max_length=3),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='SDG', max_length=3),
        ),
    ]
