# Generated by Django 5.0.6 on 2026-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_duration_based_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="kind",
            field=models.CharField(
                choices=[("sessions", "Live sessions"), ("ai_tutor", "AI tutor")],
                default="sessions",
                max_length=20,
            ),
        ),
    ]
