# Generated by Django 5.0.6 on 2026-06-27 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementResetAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('reset_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'placement_reset_audit',
                'ordering': ['-reset_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementSpokenAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript_text', models.TextField(blank=True)),
                ('stt_provider', models.CharField(blank=True, default='', max_length=40)),
                ('stt_confidence', models.FloatField(blank=True, null=True)),
                ('spoken_attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'placement_spoken_answer',
            },
        ),
        migrations.CreateModel(
            name='PlacementWrittenAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'placement_written_answer',
            },
        ),
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('assessed', 'Assessed'), ('reset', 'Reset')], db_index=True, default='in_progress', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('fallback_used', models.BooleanField(default=False)),
                ('provider_name', models.CharField(blank=True, default='', max_length=40)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='onboarding.goal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts_v2', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'placement_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementAssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('overall_conversation_score', models.PositiveSmallIntegerField(default=0)),
                ('grammar_score', models.PositiveSmallIntegerField(default=0)),
                ('vocabulary_score', models.PositiveSmallIntegerField(default=0)),
                ('fluency_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('written_score', models.PositiveSmallIntegerField(default=0)),
                ('spoken_score', models.PositiveSmallIntegerField(default=0)),
                ('spoken_capped', models.BooleanField(default=False)),
                ('spoken_ceiling', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='C1', max_length=2)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommended_focus', models.JSONField(blank=True, default=list)),
                ('recommended_conversation_topics', models.JSONField(blank=True, default=list)),
                ('recommended_instructor_difficulty', models.CharField(choices=[('supportive', 'Supportive'), ('balanced', 'Balanced'), ('challenging', 'Challenging')], default='balanced', max_length=12)),
                ('evaluator_version', models.CharField(blank=True, default='', max_length=40)),
                ('provider_name', models.CharField(blank=True, default='heuristic', max_length=40)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='placement.placementattempt')),
            ],
            options={
                'db_table': 'placement_assessment_result',
            },
        ),
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('written', 'Written'), ('spoken', 'Spoken')], db_index=True, max_length=10)),
                ('prompt', models.TextField()),
                ('skill', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('fluency', 'Fluency'), ('comprehension', 'Comprehension'), ('conversation', 'Conversation')], default='conversation', max_length=20)),
                ('cefr_band', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='A1', max_length=2)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ai_alternatives', models.JSONField(blank=True, default=list)),
                ('scoring_rubric', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True)),
                ('correct_index', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_question',
                'ordering': ['question_type', 'order'],
                'indexes': [models.Index(fields=['question_type', 'is_active'], name='placement_q_questio_3d39a2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='placementquestion',
            constraint=models.UniqueConstraint(fields=('question_type', 'order'), name='uniq_placement_question_order_per_type'),
        ),
        migrations.AddField(
            model_name='placementresetaudit',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reset_audits', to='placement.placementattempt'),
        ),
        migrations.AddField(
            model_name='placementresetaudit',
            name='reset_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementresetaudit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_reset_audits', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='placementspokenanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spoken_answers', to='placement.placementattempt'),
        ),
        migrations.AddField(
            model_name='placementspokenanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='placement.placementquestion'),
        ),
        migrations.AddField(
            model_name='placementwrittenanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_answers', to='placement.placementattempt'),
        ),
        migrations.AddField(
            model_name='placementwrittenanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='placement.placementquestion'),
        ),
        migrations.AddIndex(
            model_name='placementattempt',
            index=models.Index(fields=['student', '-started_at'], name='placement_a_student_2b1a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='placementattempt',
            index=models.Index(fields=['status'], name='placement_a_status_c5f3c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='placementattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('student',), name='uniq_active_inprogress_attempt_per_student'),
        ),
        migrations.AddIndex(
            model_name='placementassessmentresult',
            index=models.Index(fields=['cefr_level'], name='placement_a_cefr_le_7554bd_idx'),
        ),
        migrations.AddIndex(
            model_name='placementresetaudit',
            index=models.Index(fields=['student', '-reset_at'], name='placement_r_student_84f589_idx'),
        ),
        migrations.AddIndex(
            model_name='placementspokenanswer',
            index=models.Index(fields=['attempt'], name='placement_s_attempt_5158eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='placementspokenanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_spoken_answer_per_attempt_question'),
        ),
        migrations.AddIndex(
            model_name='placementwrittenanswer',
            index=models.Index(fields=['attempt'], name='placement_w_attempt_943e9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='placementwrittenanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_written_answer_per_attempt_question'),
        ),
    ]
