# Generated by Django 5.0.6 on 2026-07-02 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementspokenanswer',
            name='source',
            field=models.CharField(choices=[('voice', 'Voice'), ('manual', 'Manual')], default='manual', max_length=6),
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('finalized', 'Transcript finalized')], db_index=True, default='created', max_length=12)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_session', to='placement.placementattempt')),
            ],
            options={
                'db_table': 'placement_interview_session',
            },
        ),
    ]
