# Generated by Django 5.0.6 on 2026-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_placementspokenanswer_source_interviewsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='script_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
