# Generated by Django 5.0.6 on 2026-07-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='intro_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
