# Generated by Django 5.0.6 on 2026-07-20 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_instructorprofile_avatar_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("issuer", models.CharField(blank=True, default="", max_length=160)),
                ("issue_date", models.CharField(blank=True, default="", max_length=40)),
                (
                    "credential_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "instructor_certifications",
            },
        ),
        migrations.CreateModel(
            name="InstructorEducation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("degree", models.CharField(max_length=160)),
                ("institution", models.CharField(max_length=160)),
                ("country", models.CharField(blank=True, default="", max_length=80)),
                ("start_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "instructor_education",
            },
        ),
        migrations.CreateModel(
            name="InstructorExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=160)),
                ("position", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("from_date", models.CharField(blank=True, default="", max_length=40)),
                ("to_date", models.CharField(blank=True, default="", max_length=40)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "instructor_experience",
            },
        ),
        migrations.CreateModel(
            name="InstructorSocialLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(max_length=20)),
                ("url", models.URLField(max_length=500)),
            ],
            options={
                "db_table": "instructor_social_links",
            },
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="accept_students",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="available_for_business",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="available_for_conversation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="available_for_ielts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="city",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="cover_photo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="founding_instructor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="job_title",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="nationality",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="profile_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="show_on_landing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="instructorprofile",
            index=models.Index(
                condition=models.Q(
                    ("profile_approved", True), ("show_on_landing", True)
                ),
                fields=["-featured", "display_order", "-rating"],
                name="instructor_public_idx",
            ),
        ),
        migrations.AddField(
            model_name="instructorcertification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructorcertification",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="accounts.instructorprofile",
            ),
        ),
        migrations.AddField(
            model_name="instructorcertification",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructoreducation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructoreducation",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="accounts.instructorprofile",
            ),
        ),
        migrations.AddField(
            model_name="instructoreducation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructorexperience",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructorexperience",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience",
                to="accounts.instructorprofile",
            ),
        ),
        migrations.AddField(
            model_name="instructorexperience",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructorsociallink",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructorsociallink",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="accounts.instructorprofile",
            ),
        ),
        migrations.AddField(
            model_name="instructorsociallink",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="instructorcertification",
            index=models.Index(
                fields=["instructor", "sort_order"],
                name="instructor__instruc_bfe31e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instructoreducation",
            index=models.Index(
                fields=["instructor", "sort_order"],
                name="instructor__instruc_5530c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instructorexperience",
            index=models.Index(
                fields=["instructor", "sort_order"],
                name="instructor__instruc_7fed5d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="instructorsociallink",
            constraint=models.UniqueConstraint(
                fields=("instructor", "platform"),
                name="uniq_instructor_social_platform",
            ),
        ),
    ]
