# Generated by Django 5.0.6 on 2026-07-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_instructorcertification_instructoreducation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorprofile",
            name="avatar_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
