# Generated by Django 5.0.6 on 2026-06-25 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=160, null=True)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
                ('accent', models.CharField(blank=True, max_length=60, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'placement_attempts',
            },
        ),
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('skill', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('comprehension', 'Comprehension'), ('usage', 'Usage')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placement_questions',
            },
        ),
        migrations.CreateModel(
            name='PlacementResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('level_label', models.CharField(max_length=40)),
                ('summary', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='onboarding.placementattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'placement_results',
            },
        ),
        migrations.AddIndex(
            model_name='placementattempt',
            index=models.Index(fields=['student', '-submitted_at'], name='placement_a_student_79ab27_idx'),
        ),
        migrations.AddIndex(
            model_name='placementquestion',
            index=models.Index(condition=models.Q(('active', True)), fields=['active'], name='placement_q_active_idx'),
        ),
        migrations.AddIndex(
            model_name='placementresult',
            index=models.Index(fields=['student', '-created_at'], name='placement_r_student_63a178_idx'),
        ),
    ]
