# Generated by Django 5.0.6 on 2026-06-25 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('status', models.CharField(choices=[('open', 'Open'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='accounts.instructorprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'availability_slots',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
                ('accent', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('vocabulary', models.JSONField(default=list)),
                ('sample_prompts', models.JSONField(default=list)),
                ('published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='accounts.instructorprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('ai_generated', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='scheduling.topic')),
            ],
            options={
                'db_table': 'subtopics',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('ai_assisted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scheduling.topic')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('topic_title', models.CharField(max_length=120)),
                ('instructor_name', models.CharField(max_length=150)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('credit_refunded', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.instructorprofile')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='scheduling.availabilityslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.studentprofile')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='billing.subscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.topic')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['instructor', 'status', 'start_at'], name='slot_open_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('instructor', 'start_at'), name='uniq_slot_per_instructor_time'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gt', 0)), name='chk_slot_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['instructor'], name='topics_instruc_47b761_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(condition=models.Q(('published', True)), fields=['published', 'category'], name='topic_published_idx'),
        ),
        migrations.AddIndex(
            model_name='subtopic',
            index=models.Index(fields=['topic', 'sort_order'], name='subtopics_topic_i_06e4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'sort_order'], name='questions_topic_i_6c2d22_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(condition=models.Q(('approved', True)), fields=['topic'], name='question_approved_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('approved', False), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='chk_approved_question_has_approver'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student', '-scheduled_at'], name='bookings_student_2862bd_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['instructor', 'scheduled_at'], name='bookings_instruc_8cd5be_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(condition=models.Q(('status', 'upcoming')), fields=['status'], name='booking_upcoming_idx'),
        ),
    ]
