# Generated by Django 5.0.6 on 2026-07-15 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_payment_status'),
        ('scheduling', '0003_sessionrating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('instructor_name', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('start_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('capacity', models.PositiveIntegerField(default=6)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_sessions', to='accounts.instructorprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_sessions',
            },
        ),
        migrations.CreateModel(
            name='GroupSessionAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='scheduling.groupsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_attendances', to='accounts.studentprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_session_attendees',
            },
        ),
        migrations.AddIndex(
            model_name='groupsession',
            index=models.Index(fields=['status', 'start_at'], name='group_sessi_status_00215b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupsession',
            index=models.Index(fields=['instructor', 'start_at'], name='group_sessi_instruc_4c0d68_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupsession',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='chk_group_session_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='groupsessionattendee',
            index=models.Index(fields=['student'], name='group_sessi_student_cb6b30_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupsessionattendee',
            constraint=models.UniqueConstraint(fields=('group_session', 'student'), name='uniq_group_session_attendee'),
        ),
    ]
