# Generated by Django 5.0.6 on 2026-07-16 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_instructorprofile_avatar_url_and_more'),
        ('scheduling', '0004_groupsession_groupsessionattendee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('vacation', 'Vacation'), ('holiday', 'Holiday'), ('block', 'Block time')], max_length=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, default='', max_length=160)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='accounts.instructorprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'availability_exceptions',
                'indexes': [models.Index(fields=['instructor', 'start_at'], name='availabilit_instruc_f10a94_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='availabilityexception',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gt', models.F('start_at'))), name='chk_availability_exception_range'),
        ),
    ]
