# Generated by Django 5.0.6 on 2026-07-20 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_instructorprofile_avatar_url_and_more"),
        ("scheduling", "0005_availabilityexception_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentScheduleSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=45)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_schedule_slots",
                        to="accounts.instructorprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_slots",
                        to="scheduling.topic",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_schedule_slots",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="schedule_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="scheduling.studentscheduleslot",
            ),
        ),
        migrations.CreateModel(
            name="RecurringAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_availability",
                        to="accounts.instructorprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recurring_availability",
                "indexes": [
                    models.Index(
                        fields=["instructor", "weekday"],
                        name="recurring_a_instruc_b57338_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recurringavailability",
            constraint=models.UniqueConstraint(
                fields=("instructor", "weekday", "start_time"),
                name="uniq_recurring_window_per_instructor",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringavailability",
            constraint=models.CheckConstraint(
                check=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="chk_recurring_weekday_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringavailability",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gt", models.F("start_time"))),
                name="chk_recurring_window_range",
            ),
        ),
        migrations.AddIndex(
            model_name="studentscheduleslot",
            index=models.Index(
                fields=["student", "active"], name="student_sch_student_aae6cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentscheduleslot",
            index=models.Index(
                fields=["instructor", "weekday"], name="student_sch_instruc_4cfdcc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentscheduleslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("deleted_at__isnull", True)),
                fields=("student", "weekday", "start_time"),
                name="uniq_active_student_schedule_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentscheduleslot",
            constraint=models.CheckConstraint(
                check=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="chk_schedule_slot_weekday_range",
            ),
        ),
    ]
