# Generated by Django 5.0.6 on 2026-07-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_instructorprofile_avatar_data"),
        ("scheduling", "0008_seed_existing_schedules_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="lesson_prepared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="lesson_questions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="booking",
            name="lesson_title",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="booking",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="scheduling.topic",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="topic_title",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="studentscheduleslot",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_schedule_slots",
                to="accounts.instructorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="studentscheduleslot",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_slots",
                to="scheduling.topic",
            ),
        ),
    ]
