# Generated by Django 5.0.6 on 2026-07-21 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_instructorprofile_avatar_data"),
        ("billing", "0008_seed_ai_tutor_plans"),
        ("scheduling", "0010_platformsettings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("schedule_slot", "scheduled_at"),
                name="uniq_active_booking_per_schedule_occurrence",
            ),
        ),
    ]
