# Generated by Django 5.0.6 on 2026-07-21 18:55

from django.db import migrations, models


def bump_existing_singleton(apps, schema_editor):
    """The default is now 10. Raise any singleton still sitting at the previous
    default (1) so existing deployments pick up the new default too; leave any
    admin-chosen value other than 1 untouched."""
    PlatformSettings = apps.get_model("scheduling", "PlatformSettings")
    PlatformSettings.objects.filter(group_capacity=1).update(group_capacity=10)


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0011_booking_uniq_active_booking_per_schedule_occurrence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformsettings",
            name="group_capacity",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.RunPython(bump_existing_singleton, migrations.RunPython.noop),
    ]
